/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CodeViewer {
    }
    interface CreateConfig {
        "fileName": any;
        "triggerType": any;
    }
    interface FileExplorer {
    }
    interface MetadataResults {
        "metadata": any;
    }
    interface SelectElementItem {
        "isBoolean"?: boolean;
        "name": string;
        "selector": string;
        "selectorType": string;
        "type": string;
    }
    interface SubitemEditConfig {
        "subItem": {};
    }
}
export interface SubitemEditConfigCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSubitemEditConfigElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCodeViewerElement extends Components.CodeViewer, HTMLStencilElement {
    }
    var HTMLCodeViewerElement: {
        prototype: HTMLCodeViewerElement;
        new (): HTMLCodeViewerElement;
    };
    interface HTMLCreateConfigElement extends Components.CreateConfig, HTMLStencilElement {
    }
    var HTMLCreateConfigElement: {
        prototype: HTMLCreateConfigElement;
        new (): HTMLCreateConfigElement;
    };
    interface HTMLFileExplorerElement extends Components.FileExplorer, HTMLStencilElement {
    }
    var HTMLFileExplorerElement: {
        prototype: HTMLFileExplorerElement;
        new (): HTMLFileExplorerElement;
    };
    interface HTMLMetadataResultsElement extends Components.MetadataResults, HTMLStencilElement {
    }
    var HTMLMetadataResultsElement: {
        prototype: HTMLMetadataResultsElement;
        new (): HTMLMetadataResultsElement;
    };
    interface HTMLSelectElementItemElement extends Components.SelectElementItem, HTMLStencilElement {
    }
    var HTMLSelectElementItemElement: {
        prototype: HTMLSelectElementItemElement;
        new (): HTMLSelectElementItemElement;
    };
    interface HTMLSubitemEditConfigElement extends Components.SubitemEditConfig, HTMLStencilElement {
    }
    var HTMLSubitemEditConfigElement: {
        prototype: HTMLSubitemEditConfigElement;
        new (): HTMLSubitemEditConfigElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "code-viewer": HTMLCodeViewerElement;
        "create-config": HTMLCreateConfigElement;
        "file-explorer": HTMLFileExplorerElement;
        "metadata-results": HTMLMetadataResultsElement;
        "select-element-item": HTMLSelectElementItemElement;
        "subitem-edit-config": HTMLSubitemEditConfigElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CodeViewer {
    }
    interface CreateConfig {
        "fileName"?: any;
        "triggerType"?: any;
    }
    interface FileExplorer {
    }
    interface MetadataResults {
        "metadata"?: any;
    }
    interface SelectElementItem {
        "isBoolean"?: boolean;
        "name"?: string;
        "selector"?: string;
        "selectorType"?: string;
        "type"?: string;
    }
    interface SubitemEditConfig {
        "onUpdateSubItemState"?: (event: SubitemEditConfigCustomEvent<any>) => void;
        "subItem"?: {};
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "code-viewer": CodeViewer;
        "create-config": CreateConfig;
        "file-explorer": FileExplorer;
        "metadata-results": MetadataResults;
        "select-element-item": SelectElementItem;
        "subitem-edit-config": SubitemEditConfig;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "code-viewer": LocalJSX.CodeViewer & JSXBase.HTMLAttributes<HTMLCodeViewerElement>;
            "create-config": LocalJSX.CreateConfig & JSXBase.HTMLAttributes<HTMLCreateConfigElement>;
            "file-explorer": LocalJSX.FileExplorer & JSXBase.HTMLAttributes<HTMLFileExplorerElement>;
            "metadata-results": LocalJSX.MetadataResults & JSXBase.HTMLAttributes<HTMLMetadataResultsElement>;
            "select-element-item": LocalJSX.SelectElementItem & JSXBase.HTMLAttributes<HTMLSelectElementItemElement>;
            "subitem-edit-config": LocalJSX.SubitemEditConfig & JSXBase.HTMLAttributes<HTMLSubitemEditConfigElement>;
        }
    }
}
