/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CreateConfig {
    }
    interface FileExplorer {
    }
    interface SelectElementItem {
        "name": string;
        "selector": string;
        "selectorType": string;
        "type": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCreateConfigElement extends Components.CreateConfig, HTMLStencilElement {
    }
    var HTMLCreateConfigElement: {
        prototype: HTMLCreateConfigElement;
        new (): HTMLCreateConfigElement;
    };
    interface HTMLFileExplorerElement extends Components.FileExplorer, HTMLStencilElement {
    }
    var HTMLFileExplorerElement: {
        prototype: HTMLFileExplorerElement;
        new (): HTMLFileExplorerElement;
    };
    interface HTMLSelectElementItemElement extends Components.SelectElementItem, HTMLStencilElement {
    }
    var HTMLSelectElementItemElement: {
        prototype: HTMLSelectElementItemElement;
        new (): HTMLSelectElementItemElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "create-config": HTMLCreateConfigElement;
        "file-explorer": HTMLFileExplorerElement;
        "select-element-item": HTMLSelectElementItemElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CreateConfig {
    }
    interface FileExplorer {
    }
    interface SelectElementItem {
        "name"?: string;
        "selector"?: string;
        "selectorType"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "create-config": CreateConfig;
        "file-explorer": FileExplorer;
        "select-element-item": SelectElementItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "create-config": LocalJSX.CreateConfig & JSXBase.HTMLAttributes<HTMLCreateConfigElement>;
            "file-explorer": LocalJSX.FileExplorer & JSXBase.HTMLAttributes<HTMLFileExplorerElement>;
            "select-element-item": LocalJSX.SelectElementItem & JSXBase.HTMLAttributes<HTMLSelectElementItemElement>;
        }
    }
}
